name: Generate Snake

permissions: 
  contents: write  # Permissões para escrever no repositório

on:
  schedule:
    - cron: "0 */1 * * *"  # Corre a cada hora
  workflow_dispatch:  # Permite que a ação seja executada manualmente pela interface do GitHub

jobs:
  build:
    runs-on: ubuntu-latest  # Usar a última versão do Ubuntu

    steps:
    
      # Faz o checkout do código para o GitHub Actions poder acessar o repositório
      - uses: actions/checkout@v2
      
      # Gera o gráfico da contribuição do GitHub em formato SVG
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: CodeDias  # Substitua com seu nome de usuário no GitHub
          outputs: 
            dist/github-snake.svg  # Caminho onde o arquivo SVG será salvo

      # Verifica o status do repositório para garantir que não haja erros
      - run: git status

      # Empurra as mudanças geradas para a branch 'output' (mantenha o repositório principal limpo)
      - name: Push changes
        uses: ad-m/github-push-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output  # Push para a branch 'output'
          force: true  # Força o push mesmo que haja conflitos (cuidado com isso)

      # Publica o conteúdo gerado no GitHub Pages usando a branch 'output'
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  # A branch onde o conteúdo será empurrado
          build_dir: dist  # Diretório que contém o conteúdo gerado (SVG)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Acesso via token
